### ISSUE TITLE
Parasol pipelines Still point to dsp-example

### ISSUE THREAD

**Issue by strangiato** [redhat-ai-services/ai-accelerator-qa#1]
Pipeline still points to dsp-example as the default value in pipeline:

https://github.com/redhat-ai-services/ai-accelerator-qa/blob/f4865b4bffdb0e2c3529848641f0f6c47f3cc7f8/tenants/parasol-insurance/model-training-pipeline/base/model-retrain-pipeline.yaml#L24C1-L25C1

**Comment by gutseb** [comment]
fixed link to be using model-retrain label. 
$ grep 5000 tenants/parasol-insurance/model-training-pipeline/base/model-retrain-pipeline.yaml
    - default: 'image-registry.openshift-image-registry.svc:5000/parasol-insurance/model-retrain'
